version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - abruere
  labels:
  - "type: Dependencies"
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
